@startuml
SpringApplication -> 构造函数:
'Bob --> Alice: Authentication Response
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
构造函数 --> webApplicationType: deduceFromClasspath()

构造函数 --> setInitializers : getSpringFactoriesInstances() -->

@enduml
